spring:
  profiles:
    group:
      local: common
      prod: common

  cloud:
    gcp:
      storage:

        url: https://storage.googleapis.com/${BUCKET_NAME}/
        credentials:
          encoded-key: ${GCS_KEY}
        project-id: ${GCP_PROJECT_ID}
        bucket: ${BUCKET_NAME}

---
spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: localhost:29092
    topic:
      alarm: alarm
      debezium_post: cercat.cercat_test.post
      debezium_comment: "cercat.cercat_test.post_comment"
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      alarm: alarm
      debezium_post: cercat.cercat.post
      debezium_comment: cercat.cercat.post_comment