### DB 연결 설정 API
POST http://localhost:8090/connectors
Content-Type: application/json

{
  "name": "debezium-connector-mysql",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.hostname": "host.docker.internal",
    "database.port": "3306",
    "database.user": "mysqluser",
    "database.password": "mysqlpw",
    "database.include.list": "cercat_test",
    "table.include.list": "cercat_test.post, cercat_test.post_comment",
    "database.server.id": "184054",
    "database.server.name": "mysqlcdc",
    "topic.prefix": "cercat",
    "database.history.kafka.bootstrap.servers": "kafka-broker-1:9092",
    "database.history.kafka.topic": "dbhistory.mysqlcdc",
    "include.schema.changes": "true",
    "database.ssl.mode": "disabled",
    "database.allowPublicKeyRetrieval": "true",
    "tombstones.on.delete": "false",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "key.converter.schemas.enable": "false",
    "message.key.columns": "cercat_test.post:id;cercat_test.post_comment:post_id",
    "transforms": "addTopicPrefix,addTypeHeader",
    "transforms.addTopicPrefix.type":"org.apache.kafka.connect.transforms.RegexRouter",
    "transforms.addTopicPrefix.regex":"(.*)",
    "transforms.addTopicPrefix.replacement":"$1",
    "transforms.addTypeHeader.type": "org.apache.kafka.connect.transforms.InsertHeader",
    "transforms.addTypeHeader.header": "__TypeId__",
    "transforms.addTypeHeader.value.literal": "DebeziumEvent",
    "schema.history.internal.kafka.topic": "schemahistory.fullfillment",
    "schema.history.internal.kafka.bootstrap.servers": "kafka-broker-1:9092"
  }
}

###
# quiz cdc 설정 삭제 API
DELETE http://localhost:8090/connectors/debezium-connector-mysql