kafka:
  topic:
    alarm-events: like-created-event,comment-created-event
  consumer-group:
    alarm: alarm-group
    debezium: debezium-group

---
spring:
  config:
    activate:
      on-profile: local,alarm
  kafka:
    bootstrap-servers: localhost:29092
    topic:
      debezium_post: cercat.cercat_test.post
      debezium_comment: "cercat.cercat_test.post_comment"
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      debezium_post: cercat.cercat.post
      debezium_comment: cercat.cercat.post_comment