spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cercat_test?useSSL=false&allowPublicKeyRetrieval=true
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  kafka:
    bootstrap-servers: localhost:29092
    topic:
      alarm: alarm
      debezium_post: cercat.cercat_test.post
      debezium_comment: "cercat.cercat_test.post_comment"
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_API_KEY}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  token:
    secret-key: ${SECRET_KEY}
  access-token:
    header: Access-token
    expire-length: 259200 #3일
  refresh-token:
    header: Refresh-token

front:
  host: localhost
  port: 3000
  home-path: /home
  sign-up-path: /sign-up

redis:
  host: localhost
  port: 6379

logging:
  level:
    tracer: trace
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: trace

elasticsearch:
  client:
    host: 35.216.34.187
  host: ${ELASTICSEARCH_HOST:localhost:9200}
  port: 9200