spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    gcp:
      storage:
        url: https://storage.googleapis.com/${BUCKET_NAME}/
        credentials:
          encoded-key: ${GCS_KEY}
        project-id: ${GCP_PROJECT_ID}
        bucket: ${BUCKET_NAME}
  datasource:
    url: jdbc:h2:tcp://localhost/~/cercat_test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: debug

server:
  port: 8081

