spring:
  datasource:
    url: jdbc:mysql://${SPRING_DATABASE_HOST}:${SPRING_DATABASE_PORT}/cercat
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      alarm: alarm
      debezium_post: cercat.cercat.post
      debezium_comment: cercat.cercat.post_comment
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_API_KEY}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  token:
    secret-key: ${SECRET_KEY}
  access-token:
    header: Access-token
    expire-length: 259200 #3일
  refresh-token:
    header: Refresh-token

front:
  host: localhost
  port: 3000
  home-path: /home
  sign-up-path: /onboarding
redis:
  host: redis
  port: 6379

elasticsearch:
  host: ${ELASTICSEARCH_HOST:es:9200}