spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    open-in-view: false
  cloud:
    gcp:
      storage:
        url: https://storage.googleapis.com/${BUCKET_NAME}/
        credentials:
          encoded-key: ${GCS_KEY}
        project-id: ${GCP_PROJECT_ID}
        bucket: ${BUCKET_NAME}
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul

springdoc:
  swagger-ui:
    persist-authorization: true
    default-models-expand-depth: -1