---
spring:
  config:
    activate:
      on-profile: local
elasticsearch:
  client:
    host: ${local.ELASTIC_HOST}
    port: 9200

logging:
  level:
    tracer: trace
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace

---
spring:
  config:
    activate:
      on-profile: prod

elasticsearch:
  client:
    host: es
    port: 9200
