{
 "title": "운영 서버 모니터링",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(application)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/act-cercat/prometheus\", uri!=\"/health\", uri!~\"/v3/api-docs/.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Counts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri, method) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/act-cercat/prometheus\", uri!=\"/health\", uri!~\"/v3/api-docs/.*\", uri!=\"REDIRECTION\", uri!=\"UNKNOWN\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri, method)(http_server_requests_seconds_sum{application=\"$app_name\", uri!=\"/health\", uri!=\"/act-cercat/prometheus\", uri!~\"/v3/api-docs/.*\", uri!=\"REDIRECTION\", uri!=\"UNKNOWN\"}) / \nsum by(uri, method)(http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/health\", uri!=\"/act-cercat/prometheus\", uri!~\"/v3/api-docs/.*\", uri!=\"REDIRECTION\", uri!=\"UNKNOWN\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Exception",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$app_name\", outcome=\"SERVER_ERROR\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "오류 응답률",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$app_name\", status=~\"[45].*\", uri!=\"/act-cercat/prometheus\", uri!=\"/health\"}[5m])) / \nsum(rate(http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/act-cercat/prometheus\", uri!=\"/health\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "상태 코드별 요청 비율",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/act-cercat/prometheus\", uri!=\"/health\"} or vector(0)) / ignoring(status) group_left() \nsum(http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/act-cercat/prometheus\", uri!=\"/health\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API 평균 응답 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$app_name\", uri!=\"/act-cercat/prometheus\", uri!=\"/health\", uri!~\"/v3/api-docs/.*\", uri!=\"REDIRECTION\", uri!=\"UNKNOWN\"}[5m]) / \nrate(http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/act-cercat/prometheus\", uri!=\"/health\", uri!~\"/v3/api-docs/.*\", uri!=\"REDIRECTION\", uri!=\"UNKNOWN\"}[5m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "서버 로그",
   "type": "logs",
   "description": "운영 서버 로그",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{container_name=~\".*cercat-(blue|green).*\"}"
    }
   ]
  },
  {
   "title": "서버 에러 로그",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=~\".*cercat-(blue|green).*\"} |= \"Caused by\""
    },
    {
     "direction": "backward",
     "expr": "{container_name=~\".*cercat-(blue|green).*\"} |= \"ERROR\""
    }
   ]
  }
 ]
}