spring:
  config:
    import:
      - secret-env.yml
      - application-db.yml
      - application-gcs.yml
      - application-cache.yml
      - application-security.yml
      - application-scheduler.yml
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
springdoc:
  swagger-ui:
    persist-authorization: true
    default-models-expand-depth: -1
server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: local,test
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${local.KAKAO_API_KEY}
            redirect-uri: ${local.KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            client-secret: ${local.CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    root: INFO
    com.cos.cercat: DEBUG

front:
  scheme: ${local.FRONT_SCHEME}
  host: localhost
  home-path: /home
  sign-up-path: /onboarding
---
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${prod.KAKAO_API_KEY}
            redirect-uri: ${prod.KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            client-secret: ${prod.CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            client_name: kakao
          apple:
            client-id: ${prod.APPLE_CLIENT_ID}
            client-secret: ${prod.APPLE_CLIENT_SECRET}
            redirect-uri: ${prod.APPLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token

apple:
  url: https://appleid.apple.com
  path: AuthKey_CD286M7CY8.p8
  cid: com.cercat.services
  tid: Z7N7P8UZS9
  kid: CD286M7CY8

logging:
  level:
    root: INFO
    com.cos.cercat: DEBUG

front:
  scheme: ${prod.FRONT_SCHEME}
  host: ${prod.FRONT_HOST}
  home-path: /home
  sign-up-path: /onboarding


management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
      base-path: ${prod.MANAGEMENT_BASE_PATH}
    jmx:
      exposure:
        exclude: "*"
    access:
      default: none
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-components: never
