spring:
  profiles:
    group:
      batch: common, domain
    include:
      - jpa

  main:
    web-application-type: none

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

server:
  port: 8081