spring:
  config:
    activate:
      on-profile: local,test
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        enable.idempotence: true
        metrics.recording.level: INFO
    consumer:
      properties:
        metrics.recording.level: INFO
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      properties:
        enable.idempotence: true
        acks: all
        max.in.flight.requests.per.connection: 1
    consumer:
      properties:
        isolation.level: read_committed
