spring:
  profiles:
    group:
      local: common
      prod: common
  jpa:
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/cercat_test?useSSL=false&allowPublicKeyRetrieval=true
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 100


redis:
  host: localhost
  port: 6379

elasticsearch:
  client:
    host: ${ELASTIC_HOST}
  host: ${ELASTICSEARCH_HOST:localhost:9200}
  port: 9200

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${SPRING_DATABASE_HOST}:${SPRING_DATABASE_PORT}/cercat
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

redis:
  host: redis
  port: 6379

elasticsearch:
  client:
    host: es
  host: ${ELASTICSEARCH_HOST:es:9200}
  port: 9200