spring:
  config:
    import:
      - secret-env.yml
      - application-db.yml
      - application-cache.yml
      - application-security.yml
  application:
    name: cercat-alarm
server:
  port: 8081
redis:
  max-retry-count: 2
  key-prefix:
    alarm-events: like-created,comment-created,interest-certificate-exam-schedule
    dead-letter: alarm-events-dlq
  consumer-group:
    alarm: notifier

---
spring:
  config:
    activate:
      on-profile: local,alarm
logging:
  level:
    root: INFO
    com.cos.cercat.alarm: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod,alarm
