spring:
  config:
    import:
      - secret-env.yml
      - application-db.yml
      - application-cache.yml
      - application-security.yml
server:
  port: 8081
kafka:
  topic:
    alarm-events: like-created,comment-created,interest-certificate-exam-schedule
  consumer-group:
    alarm: alarm-group
  consumer:
    dead-letter-topic: alarm-events-dlt
    max-retries: 3
    backoff-initial-interval: 1000
    backoff-max-interval: 10000
    concurrency: 3
springdoc:
  swagger-ui:
    path: /alert/swagger-ui.html
    url: /alert/v3/api-docs
  api-docs:
    path: /alert/v3/api-docs
---
spring:
  config:
    activate:
      on-profile: local,alarm
  kafka:
    bootstrap-servers: localhost:29092

---
spring:
  config:
    activate:
      on-profile: prod,alarm
  kafka:
    bootstrap-servers: kafka:9092
