spring:
  config:
    activate:
      on-profile: local,alarm

jwt:
  secret-key: ${local.SECRET_KEY}
  access-token:
    header: Access-token
    expiration: ${local.ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    header: Refresh-token


---
spring:
  config:
    activate:
      on-profile: prod

jwt:
  secret-key: ${prod.SECRET_KEY}
  access-token:
    header: Access-token
    expiration: ${prod.ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    header: Refresh-token
