spring:
  profiles:
    group:
      local: common, domain, infra
      prod: common, domain, infra
      test: common, domain, infra
    include:
      - elasticsearch
      - jpa
      - redis
      - gcs
      - kafka

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  swagger-ui:
    persist-authorization: true
    default-models-expand-depth: -1
server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_API_KEY}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret-key: ${SECRET_KEY}
  access-token:
    header: Access-token
    expiration: 259200 #3일
  refresh-token:
    header: Refresh-token

logging:
  level:
    tracer: trace
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: trace

front:
  host: localhost
  port: 3000
  home-path: /home
  sign-up-path: /onboarding
---
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_API_KEY}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret-key: ${SECRET_KEY}
  access-token:
    header: Access-token
    expiration: 259200 #3일
  refresh-token:
    header: Refresh-token

front:
  host: localhost
  port: 3000
  home-path: /home
  sign-up-path: /onboarding