spring:
  cloud:
    gcp:
      storage:
        url: https://storage.googleapis.com/${BUCKET_NAME}/
        credentials:
          encoded-key: ${GCS_KEY}
        project-id: ${GCP_PROJECT_ID}
        bucket: ${BUCKET_NAME}
