spring:
  profiles:
    group:
      local: common, domain
      prod: common, domain
    include:
      - jpa
  main:
    web-application-type: none

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true