spring:
  profiles:
    group:
      local: common, domain
      prod: common, domain
    include:
      - jpa
      - gcs

  main:
    web-application-type: none

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

server:
  port: 8081