spring:
  profiles:
    group:
      local: common, domain
      prod: common, domain
    include:
      - elasticsearch
      - jpa
      - redis
      - gcs
      - kafka
      - sse
  main:
    web-application-type: none

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

server:
  port: 8081