spring:
  profiles:
    group:
      local: common, domain
      prod: common, domain
    include:
      - jpa

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod