spring:
  config:
    activate:
      on-profile: local
  shedlock:
    table:
      name: cercat_test.shedlock

---
spring:
  config:
    activate:
      on-profile: prod
  shedlock:
    table:
      name: cercat.shedlock