spring:
  config:
    activate:
      on-profile: local,test,alarm

redis:
  host: localhost
  port: 6379
---
spring:
  config:
    activate:
      on-profile: prod

redis:
  host: redis
  port: 6379

