spring:
  config:
    activate:
      on-profile: local, test
  data:
    redis:
      repositories:
        enabled: false

redis:
  host: localhost
  port: 6379
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      repositories:
        enabled: false

redis:
  host: redis
  port: 6379

