 name: Cercat-Alarm Build and Deploy

 on:
   push:
     paths:
       - 'applications/app-alarm/**'
       - 'supports/**'
     branches: [ main ]

 env:
   DOCKER_IMAGE: ghcr.io/jiwonkkang/cercat-alarm
   VERSION: ${{ github.sha }}
   CONTAINER_NAME: cercat-alarm

 jobs:
   build:
     name: Build
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2 # git 레파지토리를 클론하는것과 같음

       - name: Setup docker buildx
         id: buildx
         uses: docker/setup-buildx-action@v1

       - name: Cache docker layers
         uses: actions/cache@v2
         with:
           path: /tmp/.buildx-cache
           key: ${{ runner.os }}-buildx-${{ env.VERSION }}
           restore-keys: |
             ${{ runner.os }}-buildx-

       - name: Login to ghcr
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GHCR_TOKEN }}

       - name: Build and push
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           file: ./applications/app-alarm/Dockerfile
           builder: ${{ steps.buildx.outputs.name }}
           push: true
           tags: ${{ env.DOCKER_IMAGE }}:latest
   deploy:
     needs: build
     name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: Docker login
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.REMOTE_IP }}
           username: ${{ secrets.REMOTE_SSH_ID }}
           key: ${{ secrets.REMOTE_SSH_KEY }}
           port: ${{ secrets.REMOTE_SSH_PORT }}
           script: |
             sudo chmod 666 /var/run/docker.sock
             echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
       - name: Remove And Pull
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.REMOTE_IP }}
           username: ${{ secrets.REMOTE_SSH_ID }}
           key: ${{ secrets.REMOTE_SSH_KEY }}
           port: ${{ secrets.REMOTE_SSH_PORT }}
           script: |
             docker rm ${{ env.CONTAINER_NAME }} && docker rmi ${{ env.DOCKER_IMAGE }}:latest
             docker pull ${{ env.DOCKER_IMAGE }}:latest
             docker compose down ${{ env.CONTAINER_NAME }} && docker compose up -d ${{ env.CONTAINER_NAME }}
